// SPDX-License-Identifier: MIT
// REFERENCE SKETCH v3 — Linkdrop-style ephemeral link key (redesigned Oct 5
// after two rounds of external review).
//
// WHY v3: v2's relayer-submitted secret claim had a fatal redirect flaw —
// the relayer must put the secret in calldata (so it learns it), and since
// payee is attacker-chosen, the relayer could claim to itself with its own
// signature. v3 removes the shared secret entirely: the link fragment carries
// a 32-byte EPHEMERAL PRIVATE KEY ("link key"), and the claim authorization
// is a signature made BY that key. Only the signature — never the key —
// reaches the chain or the relayer, so:
//   * the relayer cannot redirect (forging a sig for a different payee
//     requires the link key, which it never sees);
//   * front-running is genuinely fund-neutral (a mempool watcher sees only
//     (id, payee, sig) — replay pays the same payee; forgery needs the key);
//   * the recipient needs zero MON (relayer submits; the link-key signature
//     is produced client-side with @noble/secp256k1 — no gas, no wallet);
//   * whoever holds the link holds the key — possession IS ownership, the
//     documented Linkdrop/cash analogy. A forwarded link = handing cash.
//
// The recipient's Mera passkey account is the DESTINATION (payee) — created
// at claim time, keeping the "fingerprint creates your wallet" demo beat.
//
// TASK-302 implements from this. Trust model: the relayer can censor/delay,
// never redirect or steal. Production: ERC-4337 paymaster or redundant
// relayers. See docs/RESEARCH_TECH.md §3, SECURITY.md, RESEARCH_SECURITY.md.
pragma solidity ^0.8.24;

import {IERC20} from "openzeppelin-contracts/token/ERC20/IERC20.sol";
import {SafeERC20} from "openzeppelin-contracts/token/ERC20/utils/SafeERC20.sol";
import {EIP712} from "openzeppelin-contracts/utils/EIP712.sol";
import {ECDSA} from "openzeppelin-contracts/utils/cryptography/ECDSA.sol";
import {MessageHashUtils} from "openzeppelin-contracts/utils/cryptography/MessageHashUtils.sol";

contract SendEscrow is EIP712 {
    using ECDSA for bytes32;
    using SafeERC20 for IERC20;

    bytes32 private constant CLAIM_TYPEHASH =
        keccak256("Claim(uint256 escrowId,address payee)");

    /// @dev minimum ttl — prevents same-block deposit+reclaim and mid-demo expiry
    uint40 public constant MIN_TTL = 10 minutes;

    struct Escrow {
        address sender;      // can cancel; reclaim target after expiry
        uint96 amount;       // AUSD, 6 decimals
        address linkKey;     // ephemeral claim key generated by the sender's app — ONLY the link fragment holds its private key
        uint64 expiresAt;    // unclaimed funds return via reclaim()
        bool claimed;
    }

    IERC20 public immutable ausd;
    uint256 public nextId;
    mapping(uint256 escrowId => Escrow) public escrows;

    // Events power the Envio indexer (TASK-605 history feed) and the Nansen
    // labels panel — off-chain consumers MUST NOT scrape state variables.
    event Deposited(uint256 indexed escrowId, address indexed sender, address indexed linkKey, uint96 amount, uint64 expiresAt);
    event Claimed(uint256 indexed escrowId, address indexed payee, uint96 amount, address indexed relayer);
    event Cancelled(uint256 indexed escrowId, address indexed sender, uint96 amount);
    event Reclaimed(uint256 indexed escrowId, uint96 amount);

    error NoEscrow();
    error AlreadyClaimed();
    error NotSender();
    error Expired();
    error NotYetExpired();
    error BadAmount();
    error TtlTooShort();
    error BadLinkKeySignature();

    constructor(address ausd_) EIP712("SendEscrow", "1") {
        ausd = IERC20(ausd_);
    }

    /// @notice sender locks AUSD against an ephemeral link key generated
    /// client-side; sender pays gas (they are the funded party). If AUSD
    /// freezes msg.sender or is paused, safeTransferFrom reverts and the
    /// WHOLE tx reverts atomically — id counter and state roll back, nothing
    /// recorded, nothing stranded.
    function depositTo(address linkKey, uint96 amount, uint40 ttl)
        external
        returns (uint256 id)
    {
        if (amount == 0) revert BadAmount();
        if (ttl < MIN_TTL) revert TtlTooShort();
        if (linkKey == address(0)) revert BadLinkKeySignature();
        id = ++nextId;
        escrows[id] = Escrow(
            msg.sender,
            amount,
            linkKey,
            uint64(block.timestamp) + ttl,
            false
        );
        ausd.safeTransferFrom(msg.sender, address(this), amount); // interaction last (CEI)
        emit Deposited(id, msg.sender, linkKey, amount, uint64(block.timestamp) + ttl);
    }

    /// @notice RELAYER submits (server wallet pays gas); the recipient needs
    /// zero MON. `payee` is the recipient's fresh Mera passkey account.
    /// `sig` is the link key's EIP-712 signature over Claim(escrowId, payee),
    /// produced client-side from the link fragment — the private key NEVER
    /// leaves the fragment, so neither the relayer nor a mempool watcher can
    /// produce a signature for any other destination. If AUSD is frozen/
    /// paused the tx reverts atomically and can be retried after unpause
    /// (or sender cancels / expiry reclaim) — nothing can strand.
    function claim(uint256 id, address payee, bytes calldata sig)
        external
    {
        Escrow storage e = escrows[id];
        if (e.sender == address(0)) revert NoEscrow();
        if (e.claimed || e.amount == 0) revert AlreadyClaimed();
        if (block.timestamp > e.expiresAt) revert Expired();
        // effects before interactions
        e.claimed = true;
        // authorization: the LINK KEY signs the destination. OZ ECDSA rejects
        // malleated/high-s signatures; the EIP-712 domain (chainId + this
        // contract) blocks cross-chain/cross-contract replay; the single-use
        // flag blocks double claims.
        bytes32 digest = _hashTypedDataV4(keccak256(abi.encode(CLAIM_TYPEHASH, id, payee)));
        if (digest.recover(sig) != e.linkKey) revert BadLinkKeySignature();
        uint96 amt = e.amount;
        e.amount = 0;
        ausd.safeTransfer(payee, amt);
        emit Claimed(id, payee, amt, msg.sender);
    }

    /// @notice sender-only refund while unclaimed (sender pays gas).
    function cancel(uint256 id) external {
        Escrow storage e = escrows[id];
        if (e.sender == address(0)) revert NoEscrow();
        if (e.sender != msg.sender) revert NotSender();
        if (e.claimed || e.amount == 0) revert AlreadyClaimed();
        e.claimed = true; // slot burned; funds out below
        uint96 amt = e.amount;
        e.amount = 0;
        ausd.safeTransfer(msg.sender, amt);
        emit Cancelled(id, msg.sender, amt);
    }

    /// @notice anyone may bounce expired funds back to the sender — a keeper
    /// or the relayer can run this; the sender need not be online.
    function reclaim(uint256 id) external {
        Escrow storage e = escrows[id];
        if (e.sender == address(0)) revert NoEscrow();
        if (block.timestamp <= e.expiresAt) revert NotYetExpired();
        if (e.claimed || e.amount == 0) revert AlreadyClaimed();
        e.claimed = true;
        uint96 amt = e.amount;
        e.amount = 0;
        ausd.safeTransfer(e.sender, amt);
        emit Reclaimed(id, amt);
    }
}
